using CsvHelper.Configuration;
using MbfApp.Data.Entities;

namespace MbfApp.Services;

public sealed class MemberLedgerMap : ClassMap<MemberLedger>
{
    public MemberLedgerMap()
    {
        Map(m => m.EmpCode);
        Map(m => m.YearMonth);
       // Map(m => m.DepositDr);
        Map(m => m.DepositCr);
       // Map(m => m.IntDeposit);
       // Map(m => m.LoanDr);
        Map(m => m.LoanCr);
       // Map(m => m.IntLoan);

        // Ignore Id (auto-generated by DB)
        Map(m => m.Id).Ignore();
    }
}